### ISSUE TITLE
Beam search?

### ISSUE THREAD

**Issue by AbhinavMadahar** [wickerlab/memento#2]
My research involves training very large models, so it's impractical for me to run a grid search. I would like to use a beam search instead, for obvious reasons. Have there been talks of implementing beam search in this library? I can go ahead and try to do so if you'd like.

**Comment by joergwicker** [comment]
Sorry, just saw this now. We did not plan another search yet and are not working on it so far, but I am happy to merge a pull request with it as a search alternative.

**Comment by AbhinavMadahar** [comment]
I think that it doesn't conceptually make sense to implement beam search here. This package evaluates different configurations to see which configurations work the best, but beam search is about hyperparamater configuration. As such, it makes more sense for me to use a different library for hyperparameter configuration.

**Comment by joergwicker** [comment]
I agree, we did not plan to use Memento in that way and many of its advantages would probably be lost in hyperparameter tuning, but it might have its use for some use case I am not thinking of right now. But as I said, we are not planning to implement it right now.

**Comment by AbhinavMadahar** [comment]
lmao kiwis on gmt+13 lol
